/*
MAINUL-X Portfolio - Chatbot Configuration
Author: Md. Mainul Islam
GitHub: https://github.com/M41NUL
⚠️ WARNING: This file is auto-generated by GitHub Actions!
Do not edit manually - changes will be overwritten.
*/

const CONFIG = {
    // Google Gemini API - from GitHub Secrets
    GEMINI_API_KEY: 'AIzaSyAUzfPSN_Ym0zcAskV8-pOkshm4mH2fiuM',
    
    // Telegram Bot Token - from GitHub Secrets
    TELEGRAM_TOKEN: '8213501580:AAFWMIzosQVBMa7CBGf66QrXKJlAUwZwyC8',
    
    // GitHub
    GITHUB_USERNAME: 'M41NUL',
    
    // Chatbot settings
    MAX_MEMORY: 10,
    TYPING_SPEED: 15,
    VOICE_LANG: 'bn-BD',
    
    // Contact info
    WHATSAPP: '01308850528',
    BKASH: '01308850528',
    NAGAD: '01308850528',
    BANK_ACCOUNT: '1073831440001',
    
    // Social links
    GITHUB_URL: 'https://github.com/m41nul',
    FACEBOOK: 'https://facebook.com/mainulxhy',
    INSTAGRAM: 'https://instagram.com/mainul_xhy',
    TELEGRAM: 'https://t.me/mdmainulislaminfo',
    FB_PAGE: 'https://facebook.com/socinestx',
    IG_BUSINESS: 'https://instagram.com/socinestx'
};

console.log('✅ Config loaded');

// For Node.js environment
if (typeof module !== 'undefined' && module.exports) {
    module.exports = CONFIG;
}
